% This test file was generated by Copilot. Validate generated output before use.
classdef AerospaceFlightDataTest < matlab.unittest.TestCase
    methods(Test)
        function testFlightTableStructure(testCase)
            % Test if the flightTable has the correct structure
            flightTable = qd.exampleData.aerospaceFlightData();

            % Verify that flightTable is a table
            testCase.verifyTrue(istable(flightTable));

            % Verify that the table has the expected number of columns
            expectedNumColumns = 6;
            actualNumColumns = width(flightTable);
            testCase.verifyEqual(actualNumColumns, expectedNumColumns);
        end

        function testFlightTableVariableNames(testCase)
            % Test if the flightTable has the correct variable names
            flightTable = qd.exampleData.aerospaceFlightData();

            expectedVariableNames = {'courses', 'heights', 'latitudes', 'longitudes', 'speeds', 'timeOfArrival'};
            actualVariableNames = flightTable.Properties.VariableNames;

            testCase.verifyEqual(actualVariableNames, expectedVariableNames);
        end

        function testFlightTableDataIntegrity(testCase)
            % Test if the flightTable contains valid data
            flightTable = qd.exampleData.aerospaceFlightData();

            % Verify that none of the columns contain NaN values
            testCase.verifyFalse(any(ismissing(flightTable),"all"));
        end
    end
end