% This test file was generated by Copilot. Validate the generated output before use.
classdef CleanFromDictionaryTest < matlab.unittest.TestCase
    methods(Test)
        function testValidKey(testCase)
            inputKey = "MathWorks"; % Assume this key exists in the dictionary
            expectedValue = "mathworks"; % Replace with the actual expected value

            actualValue = qd.cleanFromDictionary(inputKey);

            testCase.verifyEqual(actualValue, expectedValue);
        end

        function testInvalidKey(testCase)
            inputKey = "invalidKey"; % Assume this key does not exist in the dictionary

            testCase.verifyError(@() qd.cleanFromDictionary(inputKey), 'MATLAB:dictionary:ScalarKeyNotFound');
        end
    end
end