% This test file was generated by Copilot. Validate generated output before use.
classdef FinanceCreditCardTest < matlab.unittest.TestCase
    methods(Test)
        function testLoadData(testCase)
            % Test if the data is loaded correctly from the .mat file
            data = qd.exampleData.financeCreditCard();

            % Verify that the data is not empty
            testCase.verifyNotEmpty(data, 'Data should not be empty.');

            % Verify that the data is a struct (assuming the expected format)
            testCase.verifyClass(data, 'table', 'Data should be a table.');
        end
    end
end