% This test file was generated by Copilot. Validate the generated output before use.
classdef HeadRandTest < matlab.unittest.TestCase
    properties
        TestTable
    end

    methods(TestMethodSetup)
        function createTestTable(testCase)
            % Create a sample table for testing
            testCase.TestTable = table((1:10)', rand(10,1), 'VariableNames', {'ID', 'Value'});
        end
    end

    methods(Test)
        function testDefaultNumRows(testCase)
            % Test with default number of rows (8)
            result = qd.headRand(testCase.TestTable);
            testCase.verifyEqual(height(result), 8);
        end

        function testSpecifiedNumRows(testCase)
            % Test with specified number of rows (5)
            numRows = 5;
            result = qd.headRand(testCase.TestTable, numRows);
            testCase.verifyEqual(height(result), numRows);
        end

        function testNumRowsExceedsTotal(testCase)
            % Test when numRows exceeds total rows in the table
            numRows = 15;
            result = qd.headRand(testCase.TestTable, numRows);
            testCase.verifyEqual(height(result), height(testCase.TestTable));
        end

        function testRandomSelection(testCase)
            % Test that the selected rows are random
            result1 = qd.headRand(testCase.TestTable);
            result2 = qd.headRand(testCase.TestTable);
            testCase.verifyNotEqual(result1, result2, 'Rows should be randomly selected');
        end
    end
end