% This test file was generated by Copilot. Validate the generated output before use.
classdef LoadDictionaryTest < matlab.unittest.TestCase
    methods(Test)
        function testLoadDictionary(testCase)
            % Test if the loadDictionary function returns a dictionary
            actualOutput = qd.loadDictionary();
            testCase.verifyClass(actualOutput, 'dictionary');
        end

        function testDictionaryContent(testCase)
            % Test if the loaded dictionary contains expected keys
            actualOutput = qd.loadDictionary();
            expectedKeys = {'MathWorks', 'MATLAB', 'apples'}; % Replace with actual expected keys

            for i = 1:length(expectedKeys)
                testCase.verifyTrue(isKey(actualOutput, expectedKeys{i}), ...
                    sprintf('Key "%s" not found in the dictionary.', expectedKeys{i}));
            end
        end
    end
end