% This is an autogenerated sample test
classdef testheadRand < matlab.unittest.TestCase
    methods (Test)
        function testDefaultHeight(testCase)
            % Specify the input(s)
            load("patients.mat","Age","Gender","Height","SelfAssessedHealthStatus")
            vals = {'Poor','Fair','Good','Excellent'};
            SelfAssessedHealthStatus = categorical(SelfAssessedHealthStatus,vals,'Ordinal',true);
            T = table(Age,Gender,Height,SelfAssessedHealthStatus);

            % Exercise the function
            actualOutput = height(qd.headRand(T));

            % Specify the expected output(s)
            expectedOutput = 8;

            testCase.verifyEqual(actualOutput, expectedOutput);
        end

        function testNegativeNumRowsError(testCase)
            % Create a sample table for input
            T = table((1:5).', 'VariableNames', {'A'});

            try
                qd.headRand(T, -3)
            catch e
            end
            % Verify that calling headRand with negative numRows throws an error
            testCase.verifyEqual(e.identifier, 'MATLAB:validators:mustBePositive');
        end
    end
end