% This test file was generated by Copilot. Validate the generated output before use.
classdef UUIDTest < matlab.unittest.TestCase
    methods(Test)
        function testSingleUUID(testCase)
            expectedSize = [1, 1];
            actualUUIDs = qd.uuid(1);

            testCase.verifySize(actualUUIDs, expectedSize);
            testCase.verifyTrue(ischar(actualUUIDs{1}));
            testCase.verifyEqual(strlength(actualUUIDs{1}), 36);
        end

        function testMultipleUUIDs(testCase)
            numbUUID = 5;
            expectedSize = [numbUUID, 1];
            actualUUIDs = qd.uuid(numbUUID);

            testCase.verifySize(actualUUIDs, expectedSize);
            for i = 1:numbUUID
                testCase.verifyTrue(ischar(actualUUIDs{i}));
                testCase.verifyEqual(strlength(actualUUIDs{i}), 36);
            end
        end

        function testInvalidInput(testCase)
            testCase.verifyError(@() qd.uuid(0), 'MATLAB:validators:mustBePositive');
            testCase.verifyError(@() qd.uuid(-1), 'MATLAB:validators:mustBePositive');
            testCase.verifyError(@() qd.uuid(1.5), 'MATLAB:validators:mustBeInteger');
        end
    end
end