name: Build and Package MATLAB Toolbox

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run MATLAB Build
        uses: matlab-actions/run-build@v2

      - name: Upload packaged .mltbx file
        uses: actions/upload-artifact@v4
        with:
          name: matlab-toolbox
          path: |
            *.mltbx